name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code:
    name: Build and Test
    runs-on: ubuntu-latest
    container: node

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup docker container for tests
        run: docker run --name postgres -e POSTGRES_PASSWORD=docker -p 5432:5432 -d postgres

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests and coverage
        run: npm test:coveralls
